export { ReactComponent as burger } from './vek2.svg'
export { ReactComponent as dush } from './dush.svg'
export { ReactComponent as mosh } from './mosh.svg'
export { ReactComponent as bed } from './bed.svg'
export { ReactComponent as year } from './year.svg'

export { ReactComponent as dumaloq } from './dumaloq.svg'
export { ReactComponent as lov } from './lov.svg'
export { ReactComponent as arup } from './arup.svg'
export { ReactComponent as ardw } from './ardw.svg'
export { ReactComponent as houz_log } from './houz_log.svg'
export { ReactComponent as houz_txt } from './houz_txt.svg'
export { ReactComponent as houz_pls } from './houz_pls.svg'
export { ReactComponent as long_tre } from './ardw.svg'
export { ReactComponent as short_tre } from './ardw.svg'
export { ReactComponent as sm_1} from './sm_1.svg'
export { ReactComponent as sm_2} from './sm_2.svg'
export { ReactComponent as sm_3} from './sm_3.svg'
export { ReactComponent as sm_4} from './sm_4.svg'
export { ReactComponent as ctg1} from './ctg1.svg'
export { ReactComponent as ctg2} from './ctg2.svg'
export { ReactComponent as ctg3} from './ctg3.svg'
export { ReactComponent as ctg4} from './ctg4.svg'

// =======================
export { ReactComponent as share} from './share.svg'
export { ReactComponent as abet} from './abet.svg'
export { ReactComponent as window} from './window.svg'
export { ReactComponent as wifi} from './wifi.svg'
export { ReactComponent as wash} from './wash.svg'
export { ReactComponent as tv} from './tv.svg'
export { ReactComponent as bassen} from './bassen.svg'
export { ReactComponent as xamom} from './xamom.svg'

export { ReactComponent as freezer} from './freezer.svg'
export { ReactComponent as zontik} from './zontik.svg'
export { ReactComponent as mikro} from './mikro.svg'
export { ReactComponent as kir} from './kir.svg'
export { ReactComponent as fen} from './fen.svg'
export { ReactComponent as lawn} from './lawn.svg'
export { ReactComponent as gym} from './gym.svg'
export { ReactComponent as qozon} from './qozon.svg'
export { ReactComponent as kansaner} from './kansaner.svg'
export { ReactComponent as file_dow} from './file_dow.svg'
export { ReactComponent as start} from './start.svg'
export { ReactComponent as houses} from './houses.svg'
export { ReactComponent as logo} from './logo.svg'
export { ReactComponent as setting} from './setting.svg'
export { ReactComponent as search} from './filter.svg'
export { ReactComponent as searchs} from './search.svg'